//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v@@BUILD_VERSION@@ 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2005.11.16 � 06:30:29 CET 
//


package be.ac.ulg.montefiore.run.totem.util.jaxb.totemBase;


/**
 * Java content class for unit element declaration.
 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/home/lepropre/projects/run-totem/src/resources/TOTEM-base/TOTEM-base-v1_0.xsd line 23)
 * <p>
 * <pre>
 * &lt;element name="unit">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;attribute name="type" use="required" type="{}unitsType" />
 *         &lt;attribute name="value" use="required" type="{}unitsValue" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface Unit
    extends javax.xml.bind.Element, be.ac.ulg.montefiore.run.totem.util.jaxb.totemBase.UnitType
{


}
