//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.28 at 12:33:07 CET 
//


package be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl;

public class LSPBackupCreationImpl
    extends be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl
    implements be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.LSPBackupCreation, com.sun.xml.bind.RIElement, com.sun.xml.bind.JAXBObject, be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.UnmarshallableObject, be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.XMLSerializable, be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.ValidatableObject
{

    public final static java.lang.Class version = (be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.LSPBackupCreation.class);
    }

    public java.lang.String ____jaxb_ri____getNamespaceURI() {
        return "http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be";
    }

    public java.lang.String ____jaxb_ri____getLocalName() {
        return "LSPBackupCreation";
    }

    public be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.UnmarshallingEventHandler createUnmarshaller(be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.UnmarshallingContext context) {
        return new be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.Unmarshaller(context);
    }

    public void serializeBody(be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be", "LSPBackupCreation");
        super.serializeURIs(context);
        context.endNamespaceDecls();
        super.serializeAttributes(context);
        context.endAttributes();
        super.serializeBody(context);
        context.endElement();
    }

    public void serializeAttributes(be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.LSPBackupCreation.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000"
+"\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv."
+"grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000"
+"\fcontentModelt\u0000 Lcom/sun/msv/grammar/Expression;xr\u0000\u001ecom.sun."
+"msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Lj"
+"ava/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0003xppp\u0000sr\u0000\u001fcom.sun.msv.gra"
+"mmar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.BinaryExp"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1q\u0000~\u0000\u0003L\u0000\u0004exp2q\u0000~\u0000\u0003xq\u0000~\u0000\u0004ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007pps"
+"q\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000"
+"\u0007ppsq\u0000~\u0000\u0007ppsr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000"
+"\bppsq\u0000~\u0000\u0000sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000p\u0000sq\u0000~\u0000\u0007"
+"ppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/rel"
+"axng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0003L\u0000\u0004namet\u0000\u001dLcom/sun/msv/"
+"util/StringPair;xq\u0000~\u0000\u0004ppsr\u0000\"com.sun.msv.datatype.xsd.FloatTy"
+"pe\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000+com.sun.msv.datatype.xsd.FloatingNumberType"
+"\u00fc\u00e3\u00b6\u0087\u008c\u00a8|\u00e0\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000"
+"xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnam"
+"espaceUrit\u0000\u0012Ljava/lang/String;L\u0000\btypeNameq\u0000~\u0000$L\u0000\nwhiteSpacet"
+"\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://"
+"www.w3.org/2001/XMLSchemat\u0000\u0005floatsr\u00005com.sun.msv.datatype.xs"
+"d.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.dat"
+"atype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.gr"
+"ammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004ppsr\u0000\u001bcom"
+".sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000$L\u0000\fnames"
+"paceURIq\u0000~\u0000$xpq\u0000~\u0000(q\u0000~\u0000\'sq\u0000~\u0000\u0015ppsr\u0000 com.sun.msv.grammar.Attr"
+"ibuteExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0003L\u0000\tnameClassq\u0000~\u0000\u0001xq\u0000~\u0000\u0004q\u0000~\u0000\u0019ps"
+"q\u0000~\u0000\u001bppsr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~"
+"\u0000!q\u0000~\u0000\'t\u0000\u0005QNameq\u0000~\u0000+q\u0000~\u0000-sq\u0000~\u0000.q\u0000~\u00006q\u0000~\u0000\'sr\u0000#com.sun.msv.gra"
+"mmar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000$L\u0000\fnamespace"
+"URIq\u0000~\u0000$xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typ"
+"et\u0000)http://www.w3.org/2001/XMLSchema-instancesr\u00000com.sun.msv"
+".grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004sq\u0000~\u0000\u0018"
+"\u0001q\u0000~\u0000>sq\u0000~\u00008t\u0000\u0006metrict\u00009http://jaxb.model.scenario.totem.run"
+".montefiore.ulg.ac.beq\u0000~\u0000>sq\u0000~\u0000\u0015ppsq\u0000~\u0000\u0000q\u0000~\u0000\u0019p\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000\u001e"
+"sq\u0000~\u0000\u0015ppsq\u0000~\u00001q\u0000~\u0000\u0019pq\u0000~\u00003q\u0000~\u0000:q\u0000~\u0000>sq\u0000~\u00008t\u0000\u0007maxRateq\u0000~\u0000Bq\u0000~\u0000"
+">sq\u0000~\u0000\u0015ppsq\u0000~\u0000\u0000q\u0000~\u0000\u0019p\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0015ppsr\u0000 com.sun.m"
+"sv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.Un"
+"aryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0003xq\u0000~\u0000\u0004q\u0000~\u0000\u0019psq\u0000~\u00001q\u0000~\u0000\u0019psr\u00002com."
+"sun.msv.grammar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000"
+"~\u0000\u0004q\u0000~\u0000?q\u0000~\u0000Tsr\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000"
+"xq\u0000~\u00009q\u0000~\u0000>sq\u0000~\u00008t\u0000Sbe.ac.ulg.montefiore.run.totem.scenario."
+"model.jaxb.BaseLSPCreationType.DiffServTypet\u0000+http://java.su"
+"n.com/jaxb/xjc/dummy-elementssq\u0000~\u0000\u0015ppsq\u0000~\u00001q\u0000~\u0000\u0019pq\u0000~\u00003q\u0000~\u0000:q"
+"\u0000~\u0000>sq\u0000~\u00008t\u0000\tdiff-servq\u0000~\u0000Bq\u0000~\u0000>sq\u0000~\u0000\u0015ppsq\u0000~\u0000\u0000q\u0000~\u0000\u0019p\u0000sq\u0000~\u0000\u0007p"
+"psq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0015ppsq\u0000~\u0000Oq\u0000~\u0000\u0019psq\u0000~\u00001q\u0000~\u0000\u0019pq\u0000~\u0000Tq\u0000~\u0000Vq\u0000~\u0000>sq\u0000"
+"~\u00008t\u0000Vbe.ac.ulg.montefiore.run.totem.scenario.model.jaxb.Bas"
+"eLSPCreationType.AcceptedCosTypeq\u0000~\u0000Ysq\u0000~\u0000\u0015ppsq\u0000~\u00001q\u0000~\u0000\u0019pq\u0000~"
+"\u00003q\u0000~\u0000:q\u0000~\u0000>sq\u0000~\u00008t\u0000\faccepted_cosq\u0000~\u0000Bq\u0000~\u0000>sq\u0000~\u0000\u0015ppsq\u0000~\u0000\u0000q\u0000~"
+"\u0000\u0019p\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0015ppsq\u0000~\u0000Oq\u0000~\u0000\u0019psq\u0000~\u00001q\u0000~\u0000\u0019pq\u0000~\u0000Tq\u0000"
+"~\u0000Vq\u0000~\u0000>sq\u0000~\u00008t\u0000Obe.ac.ulg.montefiore.run.totem.scenario.mod"
+"el.jaxb.BaseLSPCreationType.PathTypeq\u0000~\u0000Ysq\u0000~\u0000\u0015ppsq\u0000~\u00001q\u0000~\u0000\u0019"
+"pq\u0000~\u00003q\u0000~\u0000:q\u0000~\u0000>sq\u0000~\u00008t\u0000\u0004pathq\u0000~\u0000Bq\u0000~\u0000>sq\u0000~\u0000\u0015ppsq\u0000~\u0000\u0015q\u0000~\u0000\u0019ps"
+"q\u0000~\u0000\u0000q\u0000~\u0000\u0019p\u0000sq\u0000~\u0000\u0015ppsq\u0000~\u0000Oq\u0000~\u0000\u0019psq\u0000~\u00001q\u0000~\u0000\u0019pq\u0000~\u0000Tq\u0000~\u0000Vq\u0000~\u0000>s"
+"q\u0000~\u00008t\u0000>be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.R"
+"outingAlgoq\u0000~\u0000Ysq\u0000~\u0000\u0000q\u0000~\u0000\u0019p\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0015ppsq\u0000~\u0000Oq"
+"\u0000~\u0000\u0019psq\u0000~\u00001q\u0000~\u0000\u0019pq\u0000~\u0000Tq\u0000~\u0000Vq\u0000~\u0000>sq\u0000~\u00008t\u0000Bbe.ac.ulg.montefior"
+"e.run.totem.scenario.model.jaxb.RoutingAlgoTypeq\u0000~\u0000Ysq\u0000~\u0000\u0015pp"
+"sq\u0000~\u00001q\u0000~\u0000\u0019pq\u0000~\u00003q\u0000~\u0000:q\u0000~\u0000>sq\u0000~\u00008t\u0000\u000broutingAlgoq\u0000~\u0000Bq\u0000~\u0000>sq\u0000"
+"~\u0000\u0015ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0015ppsq\u0000~\u0000Oq\u0000~\u0000\u0019psq\u0000~\u00001q\u0000~"
+"\u0000\u0019pq\u0000~\u0000Tq\u0000~\u0000Vq\u0000~\u0000>sq\u0000~\u00008t\u0000Sbe.ac.ulg.montefiore.run.totem.sc"
+"enario.model.jaxb.LSPBackupCreationType.DetourTypeq\u0000~\u0000Ysq\u0000~\u0000"
+"\u0015ppsq\u0000~\u00001q\u0000~\u0000\u0019pq\u0000~\u00003q\u0000~\u0000:q\u0000~\u0000>sq\u0000~\u00008t\u0000\u0006Detourq\u0000~\u0000Bsq\u0000~\u0000\u0000pp\u0000s"
+"q\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0015ppsq\u0000~\u0000Oq\u0000~\u0000\u0019psq\u0000~\u00001q\u0000~\u0000\u0019pq\u0000~\u0000Tq\u0000~\u0000Vq\u0000"
+"~\u0000>sq\u0000~\u00008t\u0000Sbe.ac.ulg.montefiore.run.totem.scenario.model.ja"
+"xb.LSPBackupCreationType.BypassTypeq\u0000~\u0000Ysq\u0000~\u0000\u0015ppsq\u0000~\u00001q\u0000~\u0000\u0019p"
+"q\u0000~\u00003q\u0000~\u0000:q\u0000~\u0000>sq\u0000~\u00008t\u0000\u0006Bypassq\u0000~\u0000Bsq\u0000~\u0000\u0015ppsq\u0000~\u00001q\u0000~\u0000\u0019psq\u0000~\u0000"
+"\u001bppsr\u0000!com.sun.msv.datatype.xsd.TimeType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000)com.s"
+"un.msv.datatype.xsd.DateTimeBaseType\u0014W\u001a@3\u00a5\u00b4\u00e5\u0002\u0000\u0000xq\u0000~\u0000!q\u0000~\u0000\'t\u0000"
+"\u0004timeq\u0000~\u0000+q\u0000~\u0000-sq\u0000~\u0000.q\u0000~\u0000\u00abq\u0000~\u0000\'sq\u0000~\u00008t\u0000\u0004timet\u0000\u0000q\u0000~\u0000>sq\u0000~\u0000\u0015pp"
+"sq\u0000~\u00001q\u0000~\u0000\u0019psq\u0000~\u0000\u001bppsr\u0000\'com.sun.msv.datatype.xsd.FinalCompon"
+"ent\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\nfinalValuexr\u0000\u001ecom.sun.msv.datatype.xsd.Prox"
+"y\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bbaseTypet\u0000)Lcom/sun/msv/datatype/xsd/XSDataty"
+"peImpl;xq\u0000~\u0000#q\u0000~\u0000Bt\u0000\bASIdTypeq\u0000~\u0000+sr\u0000 com.sun.msv.datatype.x"
+"sd.IntType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000+com.sun.msv.datatype.xsd.IntegerDer"
+"ivedType\u0099\u00f1]\u0090&6k\u00be\u0002\u0000\u0001L\u0000\nbaseFacetsq\u0000~\u0000\u00b5xq\u0000~\u0000!q\u0000~\u0000\'t\u0000\u0003intq\u0000~\u0000+s"
+"r\u0000*com.sun.msv.datatype.xsd.MaxInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#"
+"com.sun.msv.datatype.xsd.RangeFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\nlimitValuet"
+"\u0000\u0012Ljava/lang/Object;xr\u00009com.sun.msv.datatype.xsd.DataTypeWit"
+"hValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd"
+".DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012needValueChec"
+"kFlagL\u0000\bbaseTypeq\u0000~\u0000\u00b5L\u0000\fconcreteTypet\u0000\'Lcom/sun/msv/datatype"
+"/xsd/ConcreteType;L\u0000\tfacetNameq\u0000~\u0000$xq\u0000~\u0000#ppq\u0000~\u0000+\u0000\u0001sr\u0000*com.su"
+"n.msv.datatype.xsd.MinInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u00bdppq\u0000~\u0000+"
+"\u0000\u0000sr\u0000!com.sun.msv.datatype.xsd.LongType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u00b9q\u0000~\u0000"
+"\'t\u0000\u0004longq\u0000~\u0000+sq\u0000~\u0000\u00bcppq\u0000~\u0000+\u0000\u0001sq\u0000~\u0000\u00c3ppq\u0000~\u0000+\u0000\u0000sr\u0000$com.sun.msv.d"
+"atatype.xsd.IntegerType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u00b9q\u0000~\u0000\'t\u0000\u0007integerq\u0000~\u0000+"
+"sr\u0000,com.sun.msv.datatype.xsd.FractionDigitsFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I"
+"\u0000\u0005scalexr\u0000;com.sun.msv.datatype.xsd.DataTypeWithLexicalConst"
+"raintFacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xq\u0000~\u0000\u00c0ppq\u0000~\u0000+\u0001\u0000sr\u0000#com.sun.msv.datatype"
+".xsd.NumberType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000!q\u0000~\u0000\'t\u0000\u0007decimalq\u0000~\u0000+q\u0000~\u0000\u00d1t\u0000\u000e"
+"fractionDigits\u0000\u0000\u0000\u0000q\u0000~\u0000\u00cbt\u0000\fminInclusivesr\u0000\u000ejava.lang.Long;\u008b\u00e4\u0090"
+"\u00cc\u008f#\u00df\u0002\u0000\u0001J\u0000\u0005valuexr\u0000\u0010java.lang.Number\u0086\u00ac\u0095\u001d\u000b\u0094\u00e0\u008b\u0002\u0000\u0000xp\u0080\u0000\u0000\u0000\u0000\u0000\u0000\u0000q\u0000~\u0000"
+"\u00cbt\u0000\fmaxInclusivesq\u0000~\u0000\u00d5\u007f\u00ff\u00ff\u00ff\u00ff\u00ff\u00ff\u00ffq\u0000~\u0000\u00c6q\u0000~\u0000\u00d4sr\u0000\u0011java.lang.Intege"
+"r\u0012\u00e2\u00a0\u00a4\u00f7\u0081\u00878\u0002\u0000\u0001I\u0000\u0005valuexq\u0000~\u0000\u00d6\u0080\u0000\u0000\u0000q\u0000~\u0000\u00c6q\u0000~\u0000\u00d8sq\u0000~\u0000\u00da\u007f\u00ff\u00ff\u00ff\u0000\u0000\u0000\u0000q\u0000~\u0000-s"
+"q\u0000~\u0000.q\u0000~\u0000\u00bbq\u0000~\u0000Bsq\u0000~\u00008t\u0000\u0004ASIDq\u0000~\u0000\u00afq\u0000~\u0000>sq\u0000~\u0000\u0015ppsq\u0000~\u00001q\u0000~\u0000\u0019pq\u0000"
+"~\u0000\u001esq\u0000~\u00008t\u0000\u0002bwq\u0000~\u0000\u00afq\u0000~\u0000>sq\u0000~\u0000\u0015ppsq\u0000~\u00001q\u0000~\u0000\u0019psq\u0000~\u0000\u001bppsr\u0000$com."
+"sun.msv.datatype.xsd.BooleanType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000!q\u0000~\u0000\'t\u0000\u0007boo"
+"leanq\u0000~\u0000+q\u0000~\u0000-sq\u0000~\u0000.q\u0000~\u0000\u00e9q\u0000~\u0000\'sq\u0000~\u00008t\u0000\festablishLSPq\u0000~\u0000\u00afq\u0000~\u0000"
+">sq\u0000~\u0000\u0015ppsq\u0000~\u00001q\u0000~\u0000\u0019psq\u0000~\u0000\u001bppsr\u0000#com.sun.msv.datatype.xsd.St"
+"ringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxq\u0000~\u0000!q\u0000~\u0000\'t\u0000\u0006stringsr\u00005c"
+"om.sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0000xq\u0000~\u0000*\u0001q\u0000~\u0000-sq\u0000~\u0000.q\u0000~\u0000\u00f2q\u0000~\u0000\'sq\u0000~\u00008t\u0000\u0005lspIdq\u0000~\u0000\u00afq\u0000~\u0000>sq\u0000~\u0000"
+"\u0015ppsq\u0000~\u00001q\u0000~\u0000\u0019pq\u0000~\u00003q\u0000~\u0000:q\u0000~\u0000>sq\u0000~\u00008t\u0000\u0011LSPBackupCreationq\u0000~\u0000"
+"Bsr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTabl"
+"et\u0000/Lcom/sun/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com"
+".sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005coun"
+"tB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/Expression"
+"Pool;xp\u0000\u0000\u00008\u0001pq\u0000~\u0000\tq\u0000~\u0000\u00b0q\u0000~\u0000\u0014q\u0000~\u0000\u00edq\u0000~\u0000xq\u0000~\u0000yq\u0000~\u0000\u000fq\u0000~\u0000Qq\u0000~\u0000cq\u0000"
+"~\u0000pq\u0000~\u0000|q\u0000~\u0000\u0084q\u0000~\u0000\u0091q\u0000~\u00000q\u0000~\u0000Fq\u0000~\u0000Zq\u0000~\u0000gq\u0000~\u0000tq\u0000~\u0000\u0088q\u0000~\u0000\u0095q\u0000~\u0000\u009dq\u0000"
+"~\u0000\u00a1q\u0000~\u0000\u00f8q\u0000~\u0000\u0012q\u0000~\u0000\u000eq\u0000~\u0000\nq\u0000~\u0000Lq\u0000~\u0000`q\u0000~\u0000mq\u0000~\u0000\u0081q\u0000~\u0000\u008eq\u0000~\u0000\u009aq\u0000~\u0000\u008cq\u0000"
+"~\u0000\u0013q\u0000~\u0000\u001aq\u0000~\u0000Eq\u0000~\u0000\rq\u0000~\u0000\u0016q\u0000~\u0000Cq\u0000~\u0000\u0011q\u0000~\u0000Jq\u0000~\u0000^q\u0000~\u0000kq\u0000~\u0000\u000bq\u0000~\u0000Nq\u0000"
+"~\u0000bq\u0000~\u0000oq\u0000~\u0000{q\u0000~\u0000\u0083q\u0000~\u0000\u0090q\u0000~\u0000\u009cq\u0000~\u0000\u00a5q\u0000~\u0000\u00e4q\u0000~\u0000\fq\u0000~\u0000\u0010q\u0000~\u0000\u00e0x"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.UnmarshallingContext context) {
            super(context, "----");
        }

        protected Unmarshaller(be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        attIdx = context.getAttribute("", "bw");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "establishLSP");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "lspId");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "ASID");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "time");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("metric" == ___local)&&("http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be" == ___uri)) {
                            spawnHandlerFromEnterElement((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("maxRate" == ___local)&&("http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be" == ___uri)) {
                            spawnHandlerFromEnterElement((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("diff-serv" == ___local)&&("http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be" == ___uri)) {
                            spawnHandlerFromEnterElement((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("accepted_cos" == ___local)&&("http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be" == ___uri)) {
                            spawnHandlerFromEnterElement((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("path" == ___local)&&("http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be" == ___uri)) {
                            spawnHandlerFromEnterElement((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("routingAlgo" == ___local)&&("http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be" == ___uri)) {
                            spawnHandlerFromEnterElement((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("routingAlgo" == ___local)&&("http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be" == ___uri)) {
                            spawnHandlerFromEnterElement((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("Detour" == ___local)&&("http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be" == ___uri)) {
                            spawnHandlerFromEnterElement((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("Bypass" == ___local)&&("http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be" == ___uri)) {
                            spawnHandlerFromEnterElement((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        spawnHandlerFromEnterElement((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                        return ;
                    case  0 :
                        if (("LSPBackupCreation" == ___local)&&("http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  2 :
                        if (("LSPBackupCreation" == ___local)&&("http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  1 :
                        attIdx = context.getAttribute("", "bw");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "establishLSP");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "lspId");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "ASID");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "time");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        spawnHandlerFromLeaveElement((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                        return ;
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        if (("bw" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                            return ;
                        }
                        if (("establishLSP" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                            return ;
                        }
                        if (("lspId" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                            return ;
                        }
                        if (("ASID" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                            return ;
                        }
                        if (("time" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                            return ;
                        }
                        spawnHandlerFromEnterAttribute((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                        return ;
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        attIdx = context.getAttribute("", "bw");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "establishLSP");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "lspId");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "ASID");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "time");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        spawnHandlerFromLeaveAttribute((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                        return ;
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  1 :
                            attIdx = context.getAttribute("", "bw");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "establishLSP");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "lspId");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "ASID");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "time");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            spawnHandlerFromText((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationTypeImpl)be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.LSPBackupCreationImpl.this).new Unmarshaller(context)), 2, value);
                            return ;
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
