//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.08.31 at 12:16:28 CEST 
//


package be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb;


/**
 * Java content class for generateCPL element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/skivee/sync/run/cvs-home/run-totem/src/resources/scenario/SAMTE-Scenario-v1_0.xsd line 24)
 * <p>
 * <pre>
 * &lt;element name="generateCPL">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;extension base="{http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be}ASEventType">
 *         &lt;attribute name="fileName" type="{http://jaxb.scenario.SAMTE.repository.totem.run.montefiore.ulg.ac.be}fileNameType" default="cpl.txt" />
 *         &lt;attribute name="maxDepth" type="{http://www.w3.org/2001/XMLSchema}int" default="5" />
 *         &lt;attribute name="nbPath" type="{http://www.w3.org/2001/XMLSchema}int" default="5" />
 *         &lt;attribute name="type" type="{http://jaxb.scenario.SAMTE.repository.totem.run.montefiore.ulg.ac.be}cplType" default="SINGLE_PATH" />
 *         &lt;attribute name="verbose" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;/extension>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface GenerateCPL
    extends javax.xml.bind.Element, be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.GenerateCPLType
{


}
