//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.08.31 at 12:16:28 CEST 
//


package be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/skivee/sync/run/cvs-home/run-totem/src/resources/scenario/SAMTE-Scenario-v1_0.xsd line 56)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://jaxb.scenario.SAMTE.repository.totem.run.montefiore.ulg.ac.be}objectiveFunction" minOccurs="0"/>
 *         &lt;element name="neighbourhood" type="{http://jaxb.scenario.SAMTE.repository.totem.run.montefiore.ulg.ac.be}neighbourhoodType" minOccurs="0"/>
 *         &lt;element name="initialSolution" type="{http://jaxb.scenario.SAMTE.repository.totem.run.montefiore.ulg.ac.be}initialSolutionType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="E" type="{http://www.w3.org/2001/XMLSchema}int" default="10" />
 *       &lt;attribute name="K" type="{http://www.w3.org/2001/XMLSchema}int" default="5" />
 *       &lt;attribute name="L" type="{http://www.w3.org/2001/XMLSchema}int" default="5" />
 *       &lt;attribute name="T0" type="{http://www.w3.org/2001/XMLSchema}float" default="10.0" />
 *       &lt;attribute name="alpha" type="{http://jaxb.scenario.SAMTE.repository.totem.run.montefiore.ulg.ac.be}alphaType" default="0.8" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface SimulatedAnnealingType {


    /**
     * Gets the value of the neighbourhood property.
     * 
     * @return
     *     possible object is
     *     {@link be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.NeighbourhoodType}
     */
    be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.NeighbourhoodType getNeighbourhood();

    /**
     * Sets the value of the neighbourhood property.
     * 
     * @param value
     *     allowed object is
     *     {@link be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.NeighbourhoodType}
     */
    void setNeighbourhood(be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.NeighbourhoodType value);

    boolean isSetNeighbourhood();

    void unsetNeighbourhood();

    /**
     * Gets the value of the alpha property.
     * 
     */
    float getAlpha();

    /**
     * Sets the value of the alpha property.
     * 
     */
    void setAlpha(float value);

    boolean isSetAlpha();

    void unsetAlpha();

    /**
     * Gets the value of the k property.
     * 
     */
    int getK();

    /**
     * Sets the value of the k property.
     * 
     */
    void setK(int value);

    boolean isSetK();

    void unsetK();

    /**
     * Gets the value of the initialSolution property.
     * 
     * @return
     *     possible object is
     *     {@link be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.InitialSolutionType}
     */
    be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.InitialSolutionType getInitialSolution();

    /**
     * Sets the value of the initialSolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.InitialSolutionType}
     */
    void setInitialSolution(be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.InitialSolutionType value);

    boolean isSetInitialSolution();

    void unsetInitialSolution();

    /**
     * Gets the value of the t0 property.
     * 
     */
    float getT0();

    /**
     * Sets the value of the t0 property.
     * 
     */
    void setT0(float value);

    boolean isSetT0();

    void unsetT0();

    /**
     * Gets the value of the l property.
     * 
     */
    int getL();

    /**
     * Sets the value of the l property.
     * 
     */
    void setL(int value);

    boolean isSetL();

    void unsetL();

    /**
     * Gets the value of the objectiveFunction property.
     * 
     * @return
     *     possible object is
     *     {@link be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.ObjectiveFunction}
     *     {@link be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.ObjectiveFunctionType}
     */
    be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.ObjectiveFunctionType getObjectiveFunction();

    /**
     * Sets the value of the objectiveFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.ObjectiveFunction}
     *     {@link be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.ObjectiveFunctionType}
     */
    void setObjectiveFunction(be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.ObjectiveFunctionType value);

    boolean isSetObjectiveFunction();

    void unsetObjectiveFunction();

    /**
     * Gets the value of the e property.
     * 
     */
    int getE();

    /**
     * Sets the value of the e property.
     * 
     */
    void setE(int value);

    boolean isSetE();

    void unsetE();

}
