//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.28 at 12:33:07 CET 
//


package be.ac.ulg.montefiore.run.totem.scenario.model.jaxb;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/hakan/svn-totem/totem/trunk/run-totem/src/resources/scenario/Scenario-v1_3.xsd line 282)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be}ASEventType">
 *       &lt;attribute name="bw" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="lspId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface LSPBWChangeType
    extends be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.ASEventType
{


    /**
     * Gets the value of the lspId property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getLspId();

    /**
     * Sets the value of the lspId property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setLspId(java.lang.String value);

    boolean isSetLspId();

    void unsetLspId();

    /**
     * Gets the value of the bw property.
     * 
     */
    float getBw();

    /**
     * Sets the value of the bw property.
     * 
     */
    void setBw(float value);

    boolean isSetBw();

    void unsetBw();

}
