//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.28 at 12:33:07 CET 
//


package be.ac.ulg.montefiore.run.totem.scenario.model.jaxb;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/hakan/svn-totem/totem/trunk/run-totem/src/resources/scenario/Scenario-v1_3.xsd line 352)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be}BaseLSPCreationType">
 *       &lt;attribute name="methodType" type="{http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be}methodType" default="GLOBAL" />
 *       &lt;attribute name="protectedLSP" use="required" type="{http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be}lspIdType" />
 *       &lt;attribute name="protectionType" type="{http://jaxb.model.scenario.totem.run.montefiore.ulg.ac.be}protectionType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface LSPDetourCreationType
    extends be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.BaseLSPCreationType
{


    /**
     * Gets the value of the methodType property.
     * 
     * @return
     *     possible object is
     *     {@link be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.MethodType}
     */
    be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.MethodType getMethodType();

    /**
     * Sets the value of the methodType property.
     * 
     * @param value
     *     allowed object is
     *     {@link be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.MethodType}
     */
    void setMethodType(be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.MethodType value);

    boolean isSetMethodType();

    void unsetMethodType();

    /**
     * Gets the value of the protectedLSP property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getProtectedLSP();

    /**
     * Sets the value of the protectedLSP property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setProtectedLSP(java.lang.String value);

    boolean isSetProtectedLSP();

    void unsetProtectedLSP();

    /**
     * Gets the value of the protectionType property.
     * 
     * @return
     *     possible object is
     *     {@link be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.ProtectionType}
     */
    be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.ProtectionType getProtectionType();

    /**
     * Sets the value of the protectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.ProtectionType}
     */
    void setProtectionType(be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.ProtectionType value);

    boolean isSetProtectionType();

    void unsetProtectionType();

}
