//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.28 at 12:33:07 CET 
//


package be.ac.ulg.montefiore.run.totem.scenario.model.jaxb;


/**
 * Java content class for methodType.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *   &lt;enumeration value="LOCAL"/>
 *   &lt;enumeration value="GLOBAL"/>
 * &lt;/restriction>
 * </pre>
 * 
 */
public class MethodType {

    private final static java.util.Map valueMap = new java.util.HashMap();
    public final static java.lang.String _LOCAL = com.sun.xml.bind.DatatypeConverterImpl.installHook("LOCAL");
    public final static be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.MethodType LOCAL = new be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.MethodType(_LOCAL);
    public final static java.lang.String _GLOBAL = com.sun.xml.bind.DatatypeConverterImpl.installHook("GLOBAL");
    public final static be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.MethodType GLOBAL = new be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.MethodType(_GLOBAL);
    private final java.lang.String lexicalValue;
    private final java.lang.String value;

    protected MethodType(java.lang.String v) {
        value = v;
        lexicalValue = v;
        valueMap.put(v, this);
    }

    public java.lang.String toString() {
        return lexicalValue;
    }

    public java.lang.String getValue() {
        return value;
    }

    public final int hashCode() {
        return super.hashCode();
    }

    public final boolean equals(java.lang.Object o) {
        return super.equals(o);
    }

    public static be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.MethodType fromValue(java.lang.String value) {
        be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.MethodType t = ((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.MethodType) valueMap.get(value));
        if (t == null) {
            throw new java.lang.IllegalArgumentException();
        } else {
            return t;
        }
    }

    public static be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.MethodType fromString(java.lang.String str) {
        return fromValue(str);
    }

}
