//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.29 at 02:59:16 CET 
//


package be.ac.ulg.montefiore.run.totem.domain.model.jaxb;


/**
 * Java content class for nodeInterface complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/monfort/Projects/run-totem/src/resources/domain/Domain-v1_3.xsd line 244)
 * <p>
 * <pre>
 * &lt;complexType name="nodeInterface">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status" type="{}statusType" minOccurs="0"/>
 *         &lt;element name="ip" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>IPAddress">
 *                 &lt;attribute name="mask" use="required" type="{}IPAddressMask" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{}interfaceIdType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface NodeInterface {


    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link be.ac.ulg.montefiore.run.totem.domain.model.jaxb.StatusType}
     */
    be.ac.ulg.montefiore.run.totem.domain.model.jaxb.StatusType getStatus();

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link be.ac.ulg.montefiore.run.totem.domain.model.jaxb.StatusType}
     */
    void setStatus(be.ac.ulg.montefiore.run.totem.domain.model.jaxb.StatusType value);

    boolean isSetStatus();

    void unsetStatus();

    /**
     * Gets the value of the ip property.
     * 
     * @return
     *     possible object is
     *     {@link be.ac.ulg.montefiore.run.totem.domain.model.jaxb.NodeInterface.IpType}
     */
    be.ac.ulg.montefiore.run.totem.domain.model.jaxb.NodeInterface.IpType getIp();

    /**
     * Sets the value of the ip property.
     * 
     * @param value
     *     allowed object is
     *     {@link be.ac.ulg.montefiore.run.totem.domain.model.jaxb.NodeInterface.IpType}
     */
    void setIp(be.ac.ulg.montefiore.run.totem.domain.model.jaxb.NodeInterface.IpType value);

    boolean isSetIp();

    void unsetIp();

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getId();

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setId(java.lang.String value);

    boolean isSetId();

    void unsetId();


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/monfort/Projects/run-totem/src/resources/domain/Domain-v1_3.xsd line 248)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>IPAddress">
     *       &lt;attribute name="mask" use="required" type="{}IPAddressMask" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface IpType {


        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getValue();

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setValue(java.lang.String value);

        boolean isSetValue();

        void unsetValue();

        /**
         * Gets the value of the mask property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getMask();

        /**
         * Sets the value of the mask property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setMask(java.lang.String value);

        boolean isSetMask();

        void unsetMask();

    }

}
