//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.08.31 at 12:16:28 CEST 
//


package be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl;

public class SAMTETypeImpl
    extends be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.ASTMEventTypeImpl
    implements be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.SAMTEType, com.sun.xml.bind.JAXBObject, be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.UnmarshallableObject, be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.XMLSerializable, be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.ValidatableObject
{

    protected be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.SimulatedAnnealingType _SimulatedAnnealing;
    protected boolean has_Verbose;
    protected boolean _Verbose;
    protected boolean has_NbLSP;
    protected int _NbLSP;
    protected boolean has_NbRun;
    protected int _NbRun;
    protected java.lang.String _CplName;
    public final static java.lang.Class version = (be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.SAMTEType.class);
    }

    public be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.SimulatedAnnealingType getSimulatedAnnealing() {
        return _SimulatedAnnealing;
    }

    public void setSimulatedAnnealing(be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.SimulatedAnnealingType value) {
        _SimulatedAnnealing = value;
    }

    public boolean isSetSimulatedAnnealing() {
        return (_SimulatedAnnealing!= null);
    }

    public void unsetSimulatedAnnealing() {
        _SimulatedAnnealing = null;
    }

    public boolean isVerbose() {
        if (!has_Verbose) {
            return javax.xml.bind.DatatypeConverter.parseBoolean(com.sun.xml.bind.DatatypeConverterImpl.installHook("false"));
        } else {
            return _Verbose;
        }
    }

    public void setVerbose(boolean value) {
        _Verbose = value;
        has_Verbose = true;
    }

    public boolean isSetVerbose() {
        return has_Verbose;
    }

    public void unsetVerbose() {
        has_Verbose = false;
    }

    public int getNbLSP() {
        if (!has_NbLSP) {
            return javax.xml.bind.DatatypeConverter.parseInt(com.sun.xml.bind.DatatypeConverterImpl.installHook("5"));
        } else {
            return _NbLSP;
        }
    }

    public void setNbLSP(int value) {
        _NbLSP = value;
        has_NbLSP = true;
    }

    public boolean isSetNbLSP() {
        return has_NbLSP;
    }

    public void unsetNbLSP() {
        has_NbLSP = false;
    }

    public int getNbRun() {
        if (!has_NbRun) {
            return javax.xml.bind.DatatypeConverter.parseInt(com.sun.xml.bind.DatatypeConverterImpl.installHook("5"));
        } else {
            return _NbRun;
        }
    }

    public void setNbRun(int value) {
        _NbRun = value;
        has_NbRun = true;
    }

    public boolean isSetNbRun() {
        return has_NbRun;
    }

    public void unsetNbRun() {
        has_NbRun = false;
    }

    public java.lang.String getCplName() {
        if (_CplName == null) {
            return "cpl.txt";
        } else {
            return _CplName;
        }
    }

    public void setCplName(java.lang.String value) {
        _CplName = value;
    }

    public boolean isSetCplName() {
        return (_CplName!= null);
    }

    public void unsetCplName() {
        _CplName = null;
    }

    public be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.UnmarshallingEventHandler createUnmarshaller(be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.UnmarshallingContext context) {
        return new be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SAMTETypeImpl.Unmarshaller(context);
    }

    public void serializeBody(be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        super.serializeBody(context);
        if (_SimulatedAnnealing!= null) {
            if (_SimulatedAnnealing instanceof javax.xml.bind.Element) {
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _SimulatedAnnealing), "SimulatedAnnealing");
            } else {
                context.startElement("http://jaxb.scenario.SAMTE.repository.totem.run.montefiore.ulg.ac.be", "simulatedAnnealing");
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _SimulatedAnnealing), "SimulatedAnnealing");
                context.endNamespaceDecls();
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _SimulatedAnnealing), "SimulatedAnnealing");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _SimulatedAnnealing), "SimulatedAnnealing");
                context.endElement();
            }
        }
    }

    public void serializeAttributes(be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_CplName!= null) {
            context.startAttribute("", "cplName");
            try {
                context.text(((java.lang.String) _CplName), "CplName");
            } catch (java.lang.Exception e) {
                be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (has_NbLSP) {
            context.startAttribute("", "nbLSP");
            try {
                context.text(javax.xml.bind.DatatypeConverter.printInt(((int) _NbLSP)), "NbLSP");
            } catch (java.lang.Exception e) {
                be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (has_NbRun) {
            context.startAttribute("", "nbRun");
            try {
                context.text(javax.xml.bind.DatatypeConverter.printInt(((int) _NbRun)), "NbRun");
            } catch (java.lang.Exception e) {
                be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (has_Verbose) {
            context.startAttribute("", "verbose");
            try {
                context.text(javax.xml.bind.DatatypeConverter.printBoolean(((boolean) _Verbose)), "Verbose");
            } catch (java.lang.Exception e) {
                be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        super.serializeAttributes(context);
        if (_SimulatedAnnealing!= null) {
            if (_SimulatedAnnealing instanceof javax.xml.bind.Element) {
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _SimulatedAnnealing), "SimulatedAnnealing");
            }
        }
    }

    public void serializeURIs(be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        super.serializeURIs(context);
        if (_SimulatedAnnealing!= null) {
            if (_SimulatedAnnealing instanceof javax.xml.bind.Element) {
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _SimulatedAnnealing), "SimulatedAnnealing");
            }
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.SAMTEType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000pp"
+"sq\u0000~\u0000\u0000ppsr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001pp"
+"sq\u0000~\u0000\fsr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000\'com.su"
+"n.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fL"
+"com/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.Elemen"
+"tExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentModelq"
+"\u0000~\u0000\u0002xq\u0000~\u0000\u0003q\u0000~\u0000\u0010p\u0000sq\u0000~\u0000\fppsr\u0000 com.sun.msv.grammar.OneOrMoreEx"
+"p\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003ex"
+"pq\u0000~\u0000\u0002xq\u0000~\u0000\u0003q\u0000~\u0000\u0010psr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\u0012xq\u0000~\u0000\u0003q\u0000~\u0000\u0010psr\u00002com.sun.msv"
+".grammar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~"
+"\u0000\u000f\u0001q\u0000~\u0000\u001csr\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dc"
+"om.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.gra"
+"mmar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000\u001dq\u0000~\u0000\""
+"sr\u0000#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNa"
+"met\u0000\u0012Ljava/lang/String;L\u0000\fnamespaceURIq\u0000~\u0000$xq\u0000~\u0000\u001ft\u0000Pbe.ac.ul"
+"g.montefiore.run.totem.repository.SAMTE.scenario.jaxb.Simula"
+"tedAnnealingt\u0000+http://java.sun.com/jaxb/xjc/dummy-elementssq"
+"\u0000~\u0000\u0011q\u0000~\u0000\u0010p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000\fppsq\u0000~\u0000\u0016q\u0000~\u0000\u0010psq\u0000~\u0000\u0019q\u0000~\u0000\u0010p"
+"q\u0000~\u0000\u001cq\u0000~\u0000 q\u0000~\u0000\"sq\u0000~\u0000#t\u0000Tbe.ac.ulg.montefiore.run.totem.repos"
+"itory.SAMTE.scenario.jaxb.SimulatedAnnealingTypeq\u0000~\u0000\'sq\u0000~\u0000\fp"
+"psq\u0000~\u0000\u0019q\u0000~\u0000\u0010psr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dt"
+"t\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLc"
+"om/sun/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000\"com.sun.msv.datatype."
+"xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.Builtin"
+"AtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteTy"
+"pe\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq\u0000~\u0000$L\u0000\btypeNameq\u0000~\u0000$L\u0000\nwhiteSpacet\u0000.L"
+"com/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www"
+".w3.org/2001/XMLSchemat\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.W"
+"hiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.dataty"
+"pe.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.gramm"
+"ar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.su"
+"n.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000$L\u0000\fnamespac"
+"eURIq\u0000~\u0000$xpq\u0000~\u0000=q\u0000~\u0000<sq\u0000~\u0000#t\u0000\u0004typet\u0000)http://www.w3.org/2001/"
+"XMLSchema-instanceq\u0000~\u0000\"sq\u0000~\u0000#t\u0000\u0012simulatedAnnealingt\u0000Dhttp://"
+"jaxb.scenario.SAMTE.repository.totem.run.montefiore.ulg.ac.b"
+"eq\u0000~\u0000\"sq\u0000~\u0000\fppsq\u0000~\u0000\u0019q\u0000~\u0000\u0010psq\u0000~\u00002ppsr\u0000!com.sun.msv.datatype.x"
+"sd.TimeType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000)com.sun.msv.datatype.xsd.DateTimeB"
+"aseType\u0014W\u001a@3\u00a5\u00b4\u00e5\u0002\u0000\u0000xq\u0000~\u00007q\u0000~\u0000<t\u0000\u0004timeq\u0000~\u0000@q\u0000~\u0000Bsq\u0000~\u0000Cq\u0000~\u0000Qq\u0000~"
+"\u0000<sq\u0000~\u0000#t\u0000\u0004timet\u0000\u0000q\u0000~\u0000\"sq\u0000~\u0000\fppsq\u0000~\u0000\u0019q\u0000~\u0000\u0010psq\u0000~\u00002ppsr\u0000\'com.s"
+"un.msv.datatype.xsd.FinalComponent\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\nfinalValuexr"
+"\u0000\u001ecom.sun.msv.datatype.xsd.Proxy\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bbaseTypet\u0000)Lco"
+"m/sun/msv/datatype/xsd/XSDatatypeImpl;xq\u0000~\u00009t\u00009http://jaxb.m"
+"odel.scenario.totem.run.montefiore.ulg.ac.bet\u0000\bASIdTypeq\u0000~\u0000@"
+"sr\u0000 com.sun.msv.datatype.xsd.IntType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000+com.sun.m"
+"sv.datatype.xsd.IntegerDerivedType\u0099\u00f1]\u0090&6k\u00be\u0002\u0000\u0001L\u0000\nbaseFacetsq\u0000"
+"~\u0000[xq\u0000~\u00007q\u0000~\u0000<t\u0000\u0003intq\u0000~\u0000@sr\u0000*com.sun.msv.datatype.xsd.MaxInc"
+"lusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#com.sun.msv.datatype.xsd.RangeFace"
+"t\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\nlimitValuet\u0000\u0012Ljava/lang/Object;xr\u00009com.sun.ms"
+"v.datatype.xsd.DataTypeWithValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr"
+"\u0000*com.sun.msv.datatype.xsd.DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fis"
+"FacetFixedZ\u0000\u0012needValueCheckFlagL\u0000\bbaseTypeq\u0000~\u0000[L\u0000\fconcreteTy"
+"pet\u0000\'Lcom/sun/msv/datatype/xsd/ConcreteType;L\u0000\tfacetNameq\u0000~\u0000"
+"$xq\u0000~\u00009ppq\u0000~\u0000@\u0000\u0001sr\u0000*com.sun.msv.datatype.xsd.MinInclusiveFac"
+"et\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000dppq\u0000~\u0000@\u0000\u0000sr\u0000!com.sun.msv.datatype.xsd.Lon"
+"gType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000`q\u0000~\u0000<t\u0000\u0004longq\u0000~\u0000@sq\u0000~\u0000cppq\u0000~\u0000@\u0000\u0001sq\u0000~\u0000j"
+"ppq\u0000~\u0000@\u0000\u0000sr\u0000$com.sun.msv.datatype.xsd.IntegerType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000"
+"xq\u0000~\u0000`q\u0000~\u0000<t\u0000\u0007integerq\u0000~\u0000@sr\u0000,com.sun.msv.datatype.xsd.Fract"
+"ionDigitsFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\u0005scalexr\u0000;com.sun.msv.datatype.xs"
+"d.DataTypeWithLexicalConstraintFacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xq\u0000~\u0000gppq\u0000~\u0000@"
+"\u0001\u0000sr\u0000#com.sun.msv.datatype.xsd.NumberType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u00007q\u0000"
+"~\u0000<t\u0000\u0007decimalq\u0000~\u0000@q\u0000~\u0000xt\u0000\u000efractionDigits\u0000\u0000\u0000\u0000q\u0000~\u0000rt\u0000\fminInclu"
+"sivesr\u0000\u000ejava.lang.Long;\u008b\u00e4\u0090\u00cc\u008f#\u00df\u0002\u0000\u0001J\u0000\u0005valuexr\u0000\u0010java.lang.Numbe"
+"r\u0086\u00ac\u0095\u001d\u000b\u0094\u00e0\u008b\u0002\u0000\u0000xp\u0080\u0000\u0000\u0000\u0000\u0000\u0000\u0000q\u0000~\u0000rt\u0000\fmaxInclusivesq\u0000~\u0000|\u007f\u00ff\u00ff\u00ff\u00ff\u00ff\u00ff\u00ffq\u0000~\u0000"
+"mq\u0000~\u0000{sr\u0000\u0011java.lang.Integer\u0012\u00e2\u00a0\u00a4\u00f7\u0081\u00878\u0002\u0000\u0001I\u0000\u0005valuexq\u0000~\u0000}\u0080\u0000\u0000\u0000q\u0000~\u0000"
+"mq\u0000~\u0000\u007fsq\u0000~\u0000\u0081\u007f\u00ff\u00ff\u00ff\u0000\u0000\u0000\u0000q\u0000~\u0000Bsq\u0000~\u0000Cq\u0000~\u0000bq\u0000~\u0000]sq\u0000~\u0000#t\u0000\u0004ASIDq\u0000~\u0000Uq"
+"\u0000~\u0000\"sq\u0000~\u0000\fppsq\u0000~\u0000\u0019q\u0000~\u0000\u0010psq\u0000~\u00002ppsq\u0000~\u0000Yq\u0000~\u0000]t\u0000\bTMIdTypeq\u0000~\u0000@q"
+"\u0000~\u0000a\u0000\u0000\u0000\u0000q\u0000~\u0000Bsq\u0000~\u0000Cq\u0000~\u0000bq\u0000~\u0000]sq\u0000~\u0000#t\u0000\u0004TMIDq\u0000~\u0000Uq\u0000~\u0000\"sq\u0000~\u0000\fpp"
+"sq\u0000~\u0000\u0019q\u0000~\u0000\u0010psq\u0000~\u00002ppsq\u0000~\u0000Yq\u0000~\u0000Jt\u0000\ffileNameTypesr\u00005com.sun.ms"
+"v.datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000?"
+"sr\u0000#com.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlway"
+"sValidxq\u0000~\u00007q\u0000~\u0000<t\u0000\u0006stringq\u0000~\u0000\u0095\u0001\u0000\u0000\u0000\u0000q\u0000~\u0000Bsq\u0000~\u0000Cq\u0000~\u0000\u0098q\u0000~\u0000Jsq\u0000"
+"~\u0000#t\u0000\u0007cplNameq\u0000~\u0000Uq\u0000~\u0000\"sq\u0000~\u0000\fppsq\u0000~\u0000\u0019q\u0000~\u0000\u0010psq\u0000~\u00002ppq\u0000~\u0000aq\u0000~\u0000"
+"Bsq\u0000~\u0000Cq\u0000~\u0000bq\u0000~\u0000<sq\u0000~\u0000#t\u0000\u0005nbLSPq\u0000~\u0000Uq\u0000~\u0000\"sq\u0000~\u0000\fppsq\u0000~\u0000\u0019q\u0000~\u0000\u0010"
+"pq\u0000~\u0000\u009esq\u0000~\u0000#t\u0000\u0005nbRunq\u0000~\u0000Uq\u0000~\u0000\"sq\u0000~\u0000\fppsq\u0000~\u0000\u0019q\u0000~\u0000\u0010psq\u0000~\u00002ppsr"
+"\u0000$com.sun.msv.datatype.xsd.BooleanType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u00007q\u0000~\u0000<"
+"t\u0000\u0007booleanq\u0000~\u0000@q\u0000~\u0000Bsq\u0000~\u0000Cq\u0000~\u0000\u00abq\u0000~\u0000<sq\u0000~\u0000#t\u0000\u0007verboseq\u0000~\u0000Uq\u0000~"
+"\u0000\"sr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTab"
+"let\u0000/Lcom/sun/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-co"
+"m.sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005cou"
+"ntB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/Expressio"
+"nPool;xp\u0000\u0000\u0000\u0016\u0001pq\u0000~\u0000\u0018q\u0000~\u0000\u0015q\u0000~\u0000,q\u0000~\u0000+q\u0000~\u0000\u000bq\u0000~\u0000\bq\u0000~\u0000\u0005q\u0000~\u0000Vq\u0000~\u0000\u00a6q"
+"\u0000~\u0000\u009cq\u0000~\u0000\u008fq\u0000~\u0000\rq\u0000~\u0000\u0007q\u0000~\u00000q\u0000~\u0000\u00a2q\u0000~\u0000\u0087q\u0000~\u0000\u0006q\u0000~\u0000\u000eq\u0000~\u0000Kq\u0000~\u0000\nq\u0000~\u0000\tq"
+"\u0000~\u0000)x"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.UnmarshallingContext context) {
            super(context, "-----------------");
        }

        protected Unmarshaller(be.ac.ulg.montefiore.run.totem.util.jaxb.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SAMTETypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  12 :
                        attIdx = context.getAttribute("", "TMID");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "ASID");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "time");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        spawnHandlerFromEnterElement((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.ASTMEventTypeImpl)be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SAMTETypeImpl.this).new Unmarshaller(context)), 13, ___uri, ___local, ___qname, __atts);
                        return ;
                    case  9 :
                        attIdx = context.getAttribute("", "verbose");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 12;
                            continue outer;
                        }
                        state = 12;
                        continue outer;
                    case  13 :
                        if (("simulatedAnnealing" == ___local)&&("http://jaxb.scenario.SAMTE.repository.totem.run.montefiore.ulg.ac.be" == ___uri)) {
                            _SimulatedAnnealing = ((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingImpl) spawnChildFromEnterElement((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingImpl.class), 16, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("simulatedAnnealing" == ___local)&&("http://jaxb.scenario.SAMTE.repository.totem.run.montefiore.ulg.ac.be" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 14;
                            return ;
                        }
                        state = 16;
                        continue outer;
                    case  16 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  6 :
                        attIdx = context.getAttribute("", "nbRun");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText2(v);
                            state = 9;
                            continue outer;
                        }
                        state = 9;
                        continue outer;
                    case  14 :
                        attIdx = context.getAttribute("", "E");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "K");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "L");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "T0");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "alpha");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("objectiveFunction" == ___local)&&("http://jaxb.scenario.SAMTE.repository.totem.run.montefiore.ulg.ac.be" == ___uri)) {
                            _SimulatedAnnealing = ((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl) spawnChildFromEnterElement((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl.class), 15, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("objectiveFunction" == ___local)&&("http://jaxb.scenario.SAMTE.repository.totem.run.montefiore.ulg.ac.be" == ___uri)) {
                            _SimulatedAnnealing = ((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl) spawnChildFromEnterElement((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl.class), 15, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("neighbourhood" == ___local)&&("http://jaxb.scenario.SAMTE.repository.totem.run.montefiore.ulg.ac.be" == ___uri)) {
                            _SimulatedAnnealing = ((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl) spawnChildFromEnterElement((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl.class), 15, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("initialSolution" == ___local)&&("http://jaxb.scenario.SAMTE.repository.totem.run.montefiore.ulg.ac.be" == ___uri)) {
                            _SimulatedAnnealing = ((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl) spawnChildFromEnterElement((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl.class), 15, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _SimulatedAnnealing = ((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl) spawnChildFromEnterElement((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl.class), 15, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  0 :
                        attIdx = context.getAttribute("", "cplName");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText3(v);
                            state = 3;
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  3 :
                        attIdx = context.getAttribute("", "nbLSP");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText4(v);
                            state = 6;
                            continue outer;
                        }
                        state = 6;
                        continue outer;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Verbose = javax.xml.bind.DatatypeConverter.parseBoolean(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_Verbose = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _NbRun = javax.xml.bind.DatatypeConverter.parseInt(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_NbRun = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _CplName = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _NbLSP = javax.xml.bind.DatatypeConverter.parseInt(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_NbLSP = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  12 :
                        attIdx = context.getAttribute("", "TMID");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "ASID");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "time");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        spawnHandlerFromLeaveElement((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.ASTMEventTypeImpl)be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SAMTETypeImpl.this).new Unmarshaller(context)), 13, ___uri, ___local, ___qname);
                        return ;
                    case  9 :
                        attIdx = context.getAttribute("", "verbose");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 12;
                            continue outer;
                        }
                        state = 12;
                        continue outer;
                    case  13 :
                        state = 16;
                        continue outer;
                    case  15 :
                        if (("simulatedAnnealing" == ___local)&&("http://jaxb.scenario.SAMTE.repository.totem.run.montefiore.ulg.ac.be" == ___uri)) {
                            context.popAttributes();
                            state = 16;
                            return ;
                        }
                        break;
                    case  16 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  6 :
                        attIdx = context.getAttribute("", "nbRun");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText2(v);
                            state = 9;
                            continue outer;
                        }
                        state = 9;
                        continue outer;
                    case  14 :
                        attIdx = context.getAttribute("", "E");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "K");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "L");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "T0");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "alpha");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        _SimulatedAnnealing = ((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl) spawnChildFromLeaveElement((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl.class), 15, ___uri, ___local, ___qname));
                        return ;
                    case  0 :
                        attIdx = context.getAttribute("", "cplName");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText3(v);
                            state = 3;
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  3 :
                        attIdx = context.getAttribute("", "nbLSP");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText4(v);
                            state = 6;
                            continue outer;
                        }
                        state = 6;
                        continue outer;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  12 :
                        if (("TMID" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.ASTMEventTypeImpl)be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SAMTETypeImpl.this).new Unmarshaller(context)), 13, ___uri, ___local, ___qname);
                            return ;
                        }
                        if (("ASID" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.ASTMEventTypeImpl)be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SAMTETypeImpl.this).new Unmarshaller(context)), 13, ___uri, ___local, ___qname);
                            return ;
                        }
                        if (("time" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.ASTMEventTypeImpl)be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SAMTETypeImpl.this).new Unmarshaller(context)), 13, ___uri, ___local, ___qname);
                            return ;
                        }
                        spawnHandlerFromEnterAttribute((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.ASTMEventTypeImpl)be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SAMTETypeImpl.this).new Unmarshaller(context)), 13, ___uri, ___local, ___qname);
                        return ;
                    case  9 :
                        if (("verbose" == ___local)&&("" == ___uri)) {
                            state = 10;
                            return ;
                        }
                        state = 12;
                        continue outer;
                    case  13 :
                        state = 16;
                        continue outer;
                    case  16 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  6 :
                        if (("nbRun" == ___local)&&("" == ___uri)) {
                            state = 7;
                            return ;
                        }
                        state = 9;
                        continue outer;
                    case  14 :
                        if (("E" == ___local)&&("" == ___uri)) {
                            _SimulatedAnnealing = ((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl) spawnChildFromEnterAttribute((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl.class), 15, ___uri, ___local, ___qname));
                            return ;
                        }
                        if (("K" == ___local)&&("" == ___uri)) {
                            _SimulatedAnnealing = ((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl) spawnChildFromEnterAttribute((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl.class), 15, ___uri, ___local, ___qname));
                            return ;
                        }
                        if (("L" == ___local)&&("" == ___uri)) {
                            _SimulatedAnnealing = ((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl) spawnChildFromEnterAttribute((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl.class), 15, ___uri, ___local, ___qname));
                            return ;
                        }
                        if (("T0" == ___local)&&("" == ___uri)) {
                            _SimulatedAnnealing = ((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl) spawnChildFromEnterAttribute((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl.class), 15, ___uri, ___local, ___qname));
                            return ;
                        }
                        if (("alpha" == ___local)&&("" == ___uri)) {
                            _SimulatedAnnealing = ((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl) spawnChildFromEnterAttribute((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl.class), 15, ___uri, ___local, ___qname));
                            return ;
                        }
                        _SimulatedAnnealing = ((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl) spawnChildFromEnterAttribute((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl.class), 15, ___uri, ___local, ___qname));
                        return ;
                    case  0 :
                        if (("cplName" == ___local)&&("" == ___uri)) {
                            state = 1;
                            return ;
                        }
                        state = 3;
                        continue outer;
                    case  3 :
                        if (("nbLSP" == ___local)&&("" == ___uri)) {
                            state = 4;
                            return ;
                        }
                        state = 6;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  5 :
                        if (("nbLSP" == ___local)&&("" == ___uri)) {
                            state = 6;
                            return ;
                        }
                        break;
                    case  8 :
                        if (("nbRun" == ___local)&&("" == ___uri)) {
                            state = 9;
                            return ;
                        }
                        break;
                    case  12 :
                        attIdx = context.getAttribute("", "TMID");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "ASID");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "time");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        spawnHandlerFromLeaveAttribute((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.ASTMEventTypeImpl)be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SAMTETypeImpl.this).new Unmarshaller(context)), 13, ___uri, ___local, ___qname);
                        return ;
                    case  9 :
                        attIdx = context.getAttribute("", "verbose");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 12;
                            continue outer;
                        }
                        state = 12;
                        continue outer;
                    case  2 :
                        if (("cplName" == ___local)&&("" == ___uri)) {
                            state = 3;
                            return ;
                        }
                        break;
                    case  13 :
                        state = 16;
                        continue outer;
                    case  16 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  6 :
                        attIdx = context.getAttribute("", "nbRun");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText2(v);
                            state = 9;
                            continue outer;
                        }
                        state = 9;
                        continue outer;
                    case  14 :
                        attIdx = context.getAttribute("", "E");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "K");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "L");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "T0");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "alpha");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        _SimulatedAnnealing = ((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl) spawnChildFromLeaveAttribute((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl.class), 15, ___uri, ___local, ___qname));
                        return ;
                    case  0 :
                        attIdx = context.getAttribute("", "cplName");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText3(v);
                            state = 3;
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  11 :
                        if (("verbose" == ___local)&&("" == ___uri)) {
                            state = 12;
                            return ;
                        }
                        break;
                    case  3 :
                        attIdx = context.getAttribute("", "nbLSP");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText4(v);
                            state = 6;
                            continue outer;
                        }
                        state = 6;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  4 :
                            eatText4(value);
                            state = 5;
                            return ;
                        case  12 :
                            attIdx = context.getAttribute("", "TMID");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "ASID");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "time");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            spawnHandlerFromText((((be.ac.ulg.montefiore.run.totem.scenario.model.jaxb.impl.ASTMEventTypeImpl)be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SAMTETypeImpl.this).new Unmarshaller(context)), 13, value);
                            return ;
                        case  9 :
                            attIdx = context.getAttribute("", "verbose");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText1(v);
                                state = 12;
                                continue outer;
                            }
                            state = 12;
                            continue outer;
                        case  13 :
                            state = 16;
                            continue outer;
                        case  16 :
                            revertToParentFromText(value);
                            return ;
                        case  6 :
                            attIdx = context.getAttribute("", "nbRun");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText2(v);
                                state = 9;
                                continue outer;
                            }
                            state = 9;
                            continue outer;
                        case  14 :
                            attIdx = context.getAttribute("", "E");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "K");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "L");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "T0");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "alpha");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            _SimulatedAnnealing = ((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl) spawnChildFromText((be.ac.ulg.montefiore.run.totem.repository.SAMTE.scenario.jaxb.impl.SimulatedAnnealingTypeImpl.class), 15, value));
                            return ;
                        case  10 :
                            eatText1(value);
                            state = 11;
                            return ;
                        case  7 :
                            eatText2(value);
                            state = 8;
                            return ;
                        case  0 :
                            attIdx = context.getAttribute("", "cplName");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText3(v);
                                state = 3;
                                continue outer;
                            }
                            state = 3;
                            continue outer;
                        case  1 :
                            eatText3(value);
                            state = 2;
                            return ;
                        case  3 :
                            attIdx = context.getAttribute("", "nbLSP");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText4(v);
                                state = 6;
                                continue outer;
                            }
                            state = 6;
                            continue outer;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
